AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  websocket-api

  Sample SAM Template for websocket-api

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    ConstraintDescription: invalid environment, only [prod, stag, dev] are allowed
  Appname:
    Type: String

Globals:
  Function:
    Tracing: Active
    Timeout: 30
    Runtime: go1.x
    MemorySize: 128
    Environment:
      Variables:
        GO_ENV: !Ref Environment

Resources:

  # WEB-SOCKET ========================================
  WebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
      Name: !Sub ${Appname}-${Environment}

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref Environment
      AutoDeploy: true
      ApiId: !Ref WebSocket

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - PushToWebSocket
    Properties:
      ApiId: !Ref WebSocket


  # CONNECT ROUTE =================================

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: "$connect"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectRouteIntegration

  ConnectRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${onConnect.Arn}/invocations

  onConnect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/onConnect
      Handler: main
      Policies:
        - AWSLambdaBasicExecutionRole

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref onConnect
      Principal: apigateway.amazonaws.com


  # PUSH TO WEBSOCKET ROUTE =================================
  PushToWebSocket:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: pushtowebsocket
      AuthorizationType: NONE
      OperationName: PushToWebSocket
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref PushToWebSocketIntegration

  PushToWebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PushToWebSocketFunction.Arn}/invocations

  PushToWebSocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*
      CodeUri: ./functions/pushToWebSocket
      Handler: main
      Environment:
        Variables:
          API_GATEWAY_ID: !Ref WebSocket

  PushToWebSocketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PushToWebSocketFunction
      Principal: apigateway.amazonaws.com


  # AUTHENTICATION ====================
  Authorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: !Sub ${Appname}-${Environment}-websocket-authorizer
      ApiId: !Ref WebSocket
      AuthorizerType: REQUEST
      AuthorizerUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestAuthorizer.Arn}/invocations
      IdentitySource:
        - route.request.querystring.Auth

  RequestAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
      CodeUri: ./functions/authorizer
      Handler: main

  RequestAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Ref: RequestAuthorizer
